export const SHOW_FOOD_FILTER = "SHOW_FOOD_FILTER",
	HIDE_FOOD_FILTER = "HIDE_FOOD_FILTER",
	SHOW_DRINK_FILTER = "SHOW_DRINK_FILTER",
	HIDE_DRINK_FILTER = "HIDE_DRINK_FILTER",
	UPDATE_FOOD_LIST = "UPDATE_FOOD_LIST",
	UPDATE_DRINKS_LIST = "UPDATE_DRINKS_LIST",
	SHOW_TOAST = "SHOW_TOAST",
	HIDE_TOAST = "HIDE_TOAST";
